# Generated by Django 2.2 on 2019-05-06 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('condition', models.CharField(blank=True, choices=[('e', 'Excellent'), ('g', 'Good'), ('f', 'Fair'), ('p', 'Poor')], help_text='Asset condition', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AssetInstance',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('checked_out', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('borrower', models.CharField(blank=True, max_length=128)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Asset')),
            ],
            options={
                'ordering': ['return_date'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ManyToManyField(to='inventory.Category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
