# Generated by Django 2.2.2 on 2019-09-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190825_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ManyToManyField(to='inventory.Category'),
        ),
    ]
