# Generated by Django 2.2.2 on 2019-09-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190901_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category'),
        ),
    ]
